### ISSUE TITLE
Amount of threads

### ISSUE THREAD

**Issue by GitStudying** [cjdelisle/packetcrypt_rs#43]
Using almost any kind of miner, there is an option to use an x amount of threads when starting the miner. In Packetcrypt this is not possible yet (or I don't know how). I would really like the option of threads in the command. Yes I know using Windows task manager or other apps you can set affinity and or priority to manually to this but this is not sticking, it has to be done after every launch again. Depending on the use case this can be really frustrating in my opinion.
I think you know what I mean but for clarity an example of the implementation:
packetcrypt.exe ann --threads 4 ....
packetcrypt.exe ann --threads 6 ...

**Comment by 3rror404** [comment]
This is already implemented. Use ```-t N``` or ```--threads N``` to limit to N threads.

https://github.com/cjdelisle/packetcrypt_rs/blob/ba10674d40f4f5ee6d4fa6819d9b8ea6d942ef97/src/main.rs#L349

Example:
```
packetcrypt ann -p <your_wallet_address> pool_1 [pool_2 pool_3 pool_4] -t 8
```

It would be good to add this to the documentation.

https://github.com/pkt-cash/pkt-docs/blob/main/docs/mining/index.md

**Comment by GitStudying** [comment]
It could be me but that is not working for me. I am uising the packetcryp v0.5.1 compilation.
If I try it, it says: 
```
 .\packetcrypt.exe -t
error: Found argument '-t' which wasn't expected, or isn't valid in this context

USAGE:
    packetcrypt.exe [FLAGS] [SUBCOMMAND]

For more information try --help
```

and 
```
.\packetcrypt.exe --threads
error: Found argument '--threads' which wasn't expected, or isn't valid in this context

USAGE:
    packetcrypt.exe [FLAGS] [SUBCOMMAND]

For more information try --help```

**Comment by GitStudying** [comment]
I tried it, and you are right it works. I just used it in the wrong way when I tried it. As you say, it would be good to add this to the documentation.

**Comment by 3rror404** [comment]
Added to the documentation: https://docs.pkt.cash/en/latest/mining/#limiting-system-resources

**Comment by GitStudying** [comment]
Thank you for the fast reply and fix that is very helpful!
