### ISSUE TITLE
stats_loop does not display the Pool/URL

### ISSUE THREAD

**Issue by Knight1** [cjdelisle/packetcrypt_rs#9]
Hi!

The stats_loop does not tell the Multi-Pool Users what Pool the stats_loop is talking about. I have Statistics, but i/others do not know what pool it actually is :)

```
1619921220 INFO annmine.rs:509 45 Ke/s    2.1Mb/s     overflow: [0, 0, 0]       uploading: [416, 177, 355]          accept/reject: [626/0, 1172/0, 0/0]                 - goodrate: [100%, 100%, 100%]
```

https://github.com/cjdelisle/packetcrypt_rs/blob/8491fa6c5530d86b03fe7c3b114b7e70e695d27e/packetcrypt-annmine/src/annmine.rs#L510

Thanks again!
Tobias

**Comment by cjdelisle** [comment]
They're in the same order as you put them on the command line (at least they should be...)
I can't think of a way to put them without taking up way too much space....

**Comment by Knight1** [comment]
Yeah. Got it! Thanks!
